THUMB = 'thumb'
PEACE = 'peace'
PALM = 'palm'
FIST = 'fist'
STRAIGHT = 'straight'
NONE = 'none'

PLAY_PAUSE = 'Play/Pause'
MUTE = 'Mute'
NEXT_TRACK = 'Next Track'
CLICK_MOUSE = 'Click mouse'
MOVE_MOUSE = 'Move mouse'
