GESTURE_THUMB = 'thumb'
GESTURE_PEACE = 'peace'
GESTURE_PALM = 'palm'
GESTURE_FIST = 'fist'
GESTURE_STRAIGHT = 'straight'
GESTURE_NONE = 'none'

NO_ACTION = 'No action'
PLAY_PAUSE = 'Play/Pause'
MUTE = 'Mute'
NEXT_TRACK = 'Next Track'
CLICK_MOUSE = 'Click mouse'
MOVE_MOUSE = 'Move mouse'
